name: Deploy to Develop AWS ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: service-crud-api
  ECS_CLUSTER: aws-reto-cluster
  ECS_SERVICE: aws-reto-service
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: app
  IMAGE_TAG: ${{ github.sha }}
  ECS_TASK_FAMILY: aws-reto
  ECS_EXECUTION_ROLE_ARN: arn:aws:iam::329631044416:role/ecsTaskExecutionRole
  ECS_TASK_ROLE_ARN: arn:aws:iam::329631044416:role/ecsTaskExecutionRole
  #ECS_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:us-east-1:329631044416:targetgroup/aws-reto-tg/880f84008d932cc0
  TARGET_GROUP_NAME: aws-reto-tg
  VPC_ID: vpc-01b8127aa7dd89f60
  ECS_SECURITY_GROUPS: sg-02afeeba5bc60b439
  ECS_SUBNETS: subnet-0ab73cdc9fd2b7bc3,subnet-05df52f152922985e
  LOAD_BALANCER_NAME: aws-reto-nlb

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Tag image
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Push image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Register Task Definition
        id: task-def
        run: |
          cat <<EOF > task-definition.json
          {
            "family": "${{ env.ECS_TASK_FAMILY }}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "${{ env.ECS_EXECUTION_ROLE_ARN }}",
            "taskRoleArn": "${{ env.ECS_TASK_ROLE_ARN }}",
            "containerDefinitions": [
              {
                "name": "${{ env.CONTAINER_NAME }}",
                "image": "nginx:latest",
                "portMappings": [
                  {
                    "containerPort": 80,
                    "protocol": "tcp"
                  }
                ],
                "essential": true
              }
            ]
          }
          EOF

          aws ecs register-task-definition --cli-input-json file://task-definition.json


      - name: Create Target Group if not exists (NLB)
        run: |
          echo "Checking if Target Group exists..."

          TARGET_GROUP_ARN=$(aws elbv2 describe-target-groups \
            --names ${{ env.TARGET_GROUP_NAME }} \
            --query "TargetGroups[0].TargetGroupArn" \
            --output text 2>/dev/null || echo "NOT_FOUND")

          if [ "$TARGET_GROUP_ARN" = "None" ] || [ "$TARGET_GROUP_ARN" = "NOT_FOUND" ]; then
            echo "Target Group does not exist. Creating..."

            TARGET_GROUP_ARN=$(aws elbv2 create-target-group \
              --name ${{ env.TARGET_GROUP_NAME }} \
              --protocol TCP \
              --port 80 \
              --vpc-id ${{ env.VPC_ID }} \
              --target-type ip \
              --query "TargetGroups[0].TargetGroupArn" \
              --output text)

            echo "Target Group created: $TARGET_GROUP_ARN"
          else
            echo "Target Group already exists: $TARGET_GROUP_ARN"

            echo "Checking Load Balancer..."
  
            LOAD_BALANCER_ARN=$(aws elbv2 describe-load-balancers \
              --names ${{ env.LOAD_BALANCER_NAME }} \
              --query "LoadBalancers[0].LoadBalancerArn" \
              --output text)
  
            echo "Load Balancer ARN: $LOAD_BALANCER_ARN"
  
            echo "Checking if Listener exists on port 80..."
  
            LISTENER_ARN=$(aws elbv2 describe-listeners \
              --load-balancer-arn $LOAD_BALANCER_ARN \
              --query "Listeners[?Port==\`80\`].ListenerArn" \
              --output text)
  
            if [ -z "$LISTENER_ARN" ]; then
              echo "Listener not found. Creating Listener on port 80..."
  
              aws elbv2 create-listener \
                --load-balancer-arn $LOAD_BALANCER_ARN \
                --protocol TCP \
                --port 80 \
                --default-actions Type=forward,TargetGroupArn=${{ env.TARGET_GROUP_ARN }}
  
              echo "Listener created."
            else
              echo "Listener already exists: $LISTENER_ARN"
            fi
            
          fi

          echo "TARGET_GROUP_ARN=$TARGET_GROUP_ARN" >> $GITHUB_ENV

      - name: Create or Update Service
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }} \
            --query "services[0].status" \
            --output text 2>/dev/null || echo "MISSING")

          if [ "$SERVICE_EXISTS" = "ACTIVE" ]; then
            echo "Updating existing service..."
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service ${{ env.ECS_SERVICE }} \
              --force-new-deployment
          else
            echo "Creating new service..."
            aws ecs create-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service-name ${{ env.ECS_SERVICE }} \
              --task-definition ${{ env.ECS_TASK_FAMILY }} \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${{ env.ECS_SUBNETS }}],securityGroups=[${{ env.ECS_SECURITY_GROUPS }}],assignPublicIp=ENABLED}" \
              --load-balancers targetGroupArn=$TARGET_GROUP_ARN,containerName=${{ env.CONTAINER_NAME }},containerPort=80
          fi

