name: Deploy to Develop AWS ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: service-crud-api
  ECS_CLUSTER: aws-reto-cluster
  ECS_SERVICE: service-crud-api
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: service-crud-api
  IMAGE_TAG: ${{ github.sha }}
  ECS_TASK_FAMILY: crud-api-task
  ECS_EXECUTION_ROLE_ARN: arn:aws:iam::329631044416:role/ecsTaskExecutionRole
  ECS_TASK_ROLE_ARN: arn:aws:iam::329631044416:role/ecsTaskExecutionRole  
  ECS_TARGET_GROUP_ARN: arn:aws:elasticloadbalancing:us-east-1:329631044416:targetgroup/aws-reto-tg/045925905048526e
  ECS_SECURITY_GROUPS: sg-06f32d75906a62974
  ECS_SUBNETS: subnet-042b15b56482db601,subnet-005479f27be7321cf

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Tag image
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Push image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Register Task Definition
        id: task-def
        run: |
          cat <<EOF > task-definition.json
          {
            "family": "${{ env.ECS_TASK_FAMILY }}",
            "networkMode": "awsvpc",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "${{ env.ECS_EXECUTION_ROLE_ARN }}",
            "taskRoleArn": "${{ env.ECS_TASK_ROLE_ARN }}",
            "containerDefinitions": [
              {
                "name": "${{ env.CONTAINER_NAME }}",
                "image": "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG",
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "protocol": "tcp"
                  }
                ],
                "essential": true
              }
            ]
          }
          EOF

          aws ecs register-task-definition --cli-input-json file://task-definition.json

      - name: Create or Update Service
        run: |
          TARGET_GROUP_ARN=$(aws elbv2 describe-target-groups \
            --names aws-reto-tg \
            --query "TargetGroups[0].TargetGroupArn" \
            --output text)
  
          SERVICE_EXISTS=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE }} \
            --query "services[0].status" \
            --output text || echo "MISSING")

          if [ "$SERVICE_EXISTS" = "ACTIVE" ]; then
            echo "Updating existing service..."
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service ${{ env.ECS_SERVICE }} \
              --force-new-deployment
          else
            echo "Creating new service..."
            aws ecs create-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service-name ${{ env.ECS_SERVICE }} \
              --task-definition ${{ env.ECS_TASK_FAMILY }} \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${{ env.ECS_SUBNETS }}],securityGroups=[${{ env.ECS_SECURITY_GROUPS }}],assignPublicIp=ENABLED}" \
              --load-balancers targetGroupArn=$TARGET_GROUP_ARN,containerName=${{ env.CONTAINER_NAME }},containerPort=8080
          fi


